src/features/chat/chat-services/chat-thread-service.ts
Also removed the unnecessary recasting of chat name, category, prompts, selected prompts and previous chat name from the upsertthread function
=> Amended chat thread name update to include storing previous name

src/features/ui/modal.tsx
This pull request includes a minor change to the `Modal` function in the `src/features/ui/modal.tsx` file. The change modifies the `Typography` component's className from `text-primary` to `text-secondary`, which will likely alter the color of the text in the feedback heading.
=> Update feedbackHeading variant to use text-secondary color in modal.tsx

src/features/chat/chat-services/chat-thread-service.ts
This pull request primarily focuses on refactoring the `src/features/chat/chat-services/chat-thread-service.ts` file. The changes involve reorganization of import statements and an update to the `InitChatSession` function.
Here's a summary of the most important changes:
* [`src/features/chat/chat-services/chat-thread-service.ts`](diffhunk://#diff-bddad34450c7e7af3d06ffd22ebcde980e85c8af1017de49bfc10f96c7084758R5-R7): The import statements for `FindAllChatDocumentsForCurrentUser` and `FindAllChatMessagesForCurrentUser` were moved to the top of the file to improve code readability and maintainability. [[1]](diffhunk://#diff-bddad34450c7e7af3d06ffd22ebcde980e85c8af1017de49bfc10f96c7084758R5-R7) [[2]](diffhunk://#diff-bddad34450c7e7af3d06ffd22ebcde980e85c8af1017de49bfc10f96c7084758L26-L28)
* …
=> Refactor chat services and import statements in chat-thread-service.ts

src/app/unauthorised/layout.tsx
This pull request includes a minor spelling correction in the `src/app/unauthorised/layout.tsx` file. The words "Unathorised" were corrected to "Unauthorised" in both the `title` and `description` fields of the `metadata` object.
=> Fix typo in page title for Unauthorised

src/next.config.js
This pull request includes a change to the `Content-Security-Policy` in the `securityHeaders` constant within the `src/next.config.js` file. The change modifies the allowed connections for the application by updating the `connect-src` directive in the policy. The directive now allows connections to any subdomain of `*.applicationinsights.azure.com`, rather than just to specific subdomains.
=> chore: Update connect-src in Content-Security-Policy header

src/next.config.js
This pull request involves a change in the Content Security Policy (CSP) in the `src/next.config.js` file. The CSP is an important security feature that helps prevent a wide range of security threats, including cross-site scripting (XSS), clickjacking, and other code injection attacks. The change in this pull request modifies the `script-src` and `connect-src` directives of the CSP.
* [`src/next.config.js`](diffhunk://#diff-c7ecd7b684200d677fdfca50895b9549ac853ccb5f3665f3fe0cf27081f6b892L27-R27): The `script-src` directive, which controls which scripts the protected resource can execute, was updated to include `https://www.google-analytics.com/` as a trusted source. The `connect-src` directive, which controls which URLs the protected resource can load using script interfaces, was updated …
=> Google Tag Manager Changes

LICENSE
This pull request updates the license information in the codebase to reflect the use of the MIT License. Additionally, it adds attribution to the Queensland Government as the original authors and contributors of the software. This change ensures compliance with open-source licensing requirements and acknowledges the Queensland Government's commitment to supporting open-source initiatives and improving public services through shared knowledge and technology.
=> Update license information and add attribution to Queensland Government

src/components/hooks/use-chat-scroll-anchor.tsx, src/features/chat/chat-ui/chat-message-container.tsx
This pull request contains changes to the `src/components/hooks/use-chat-scroll-anchor.tsx` and `src/features/chat/chat-ui/chat-message-container.tsx` files. The changes primarily focus on modifying the `useChatScrollAnchor` hook and the `ChatMessageContainer` component to control the scrolling behavior based on the loading state.
Fixes https://github.com/QDAP-DATAAI/qchat/issues/88
Here are the most important changes:
* [`src/components/hooks/use-chat-scroll-anchor.tsx`](diffhunk://#diff-93d2674ef068f36aec5e73a788c03d1bb5275c18f3fe34f7d27e1b17d2a5b2b0L6-R11): The `useChatScrollAnchor` hook was modified to accept a new `enabled` parameter. This parameter is used to control whether the chat should auto-scroll to the bottom. If `enabled` is `true`, the chat will auto-scroll to the bottom. …
=> disabled auto scroll if user scrolled up while loading

src/features/user-management/user-service.ts
The most important change is the removal of the `id` assignment when creating a new user record.
Creates item with hashed id
Changes:
* [`src/features/user-management/user-service.ts`](diffhunk://#diff-f920b8023676a47af86171079ecb6c563ef26918258b3ffe428ed0b4d518e2e3L17): Removed the line of code that assigns the `id` of the new user record to `user.upn` in the `CreateUser` function. This change suggests that the `id` of a new user record will no longer be explicitly set to the `upn` of the user.
=> fix: Remove unnecessary id assignment in CreateUser function

src/features/chat/chat-services/chat-translator-service.ts, src/tests/unit/translator.test.ts
This pull request includes changes to the `src/features/chat/chat-services/chat-translator-service.ts` and `src/tests/unit/translator.test.ts` files. The changes focus on improving the translation function and adding corresponding tests. 
Here are the key changes:
Improvements to the translation function:
* [`src/features/chat/chat-services/chat-translator-service.ts`](diffhunk://#diff-28da5da839d420338ed3564665dc2cd259d048b92b75cac5bf6c568c3fa52170R67-R80): Added a condition to check if the number of words in the original and translated texts are different. If they are, the translation is skipped for the time being. This change helps to prevent incorrect translations when the word count differs between the original and translated text.
Additions to the test suite:
* …
=> QS-366_ bugFixed

src/features/chat/chat-services/chat-api-helper.ts, src/features/chat/chat-services/chat-api.ts
This pull request primarily focuses on the addition of a `context` variable in the `ChatApi` and `buildDataChatMessages` functions in the `chat-api.ts` and `chat-api-helper.ts` files respectively. The `context` variable is used to store relevant documents related to the last chat message and is passed through various functions to be used in the `ChatApi` function.
Addition of `context` variable:
* [`src/features/chat/chat-services/chat-api-helper.ts`](diffhunk://#diff-6d77056e441a1e3e83af3fb3c1d13c45e30a871dc6fe39be966b224dd004d3ffR84): The `buildDataChatMessages` function now returns a `context` variable that is assigned the value of `relevantDocuments`, which contains documents relevant to the last chat message. [[1]](diffhunk://#diff-6d77056e441a1e3e83af3fb3c1d13c45e30a871dc6fe39be966b2 …
=> save context to chat message

src/features/settings/tenant-details/administrators.tsx
This pull request includes changes to the `Administrators` component in the `src/features/settings/tenant-details/administrators.tsx` file. The changes add a conditional rendering block that shows more or less information based on the length of the `administrators` array.
Key changes:
* [`src/features/settings/tenant-details/administrators.tsx`](diffhunk://#diff-6ac15ff5bce73aa784fddeb562d71df105df07f61f5d562fc62eeb9036d6733eR22): Added a conditional rendering block that checks if the length of the `administrators` array is greater than `DEFAULT_ITEMS_TO_SHOW`. If true, it renders a "Show More" or "Show Less" button along with a `ChevronUpIcon`. [[1]](diffhunk://#diff-6ac15ff5bce73aa784fddeb562d71df105df07f61f5d562fc62eeb9036d6733eR22) …
=> feat: Add show more/less functionality to administrators list

src/app/api/application/[content]/route.ts, src/app/page.tsx, src/components/announcement/agree-terms-and-conditions.tsx, src/components/announcement/whats-new-modal.tsx, src/components/markdown/config.tsx, src/features/chat/chat-ui/markdown/citation-slider.tsx, src/features/chat/chat-ui/markdown/citation.tsx, src/features/globals/global-message-context.tsx, src/features/globals/providers.tsx, src/features/ui/user-login-logout.tsx, src/middleware.ts, src/package.json
This pull request primarily involves refactoring and reorganization of the citation handling in the markdown feature of the chat UI. The `citation` object has been moved from `src/features/chat/chat-ui/markdown/citation.tsx` to `src/components/markdown/config.tsx`. Additionally, the `use client` directive has been shifted between these two files. The `Announcements` component in `src/features/globals/providers.tsx` has also been moved within the `Providers` component.
Refactoring and reorganization:
* [`src/components/markdown/config.tsx`](diffhunk://#diff-cfd70dc08e0f33c6327be848091775738683b5d962cbd65f7a8c951b6b8ba82eL3-R15): The `citation` object was added to this file. It was previously in `src/features/chat/chat-ui/markdown/citation.tsx`.
* …
=> fix: Announcement dialogs behaviour & Citation component

src/app/settings/admin/selectors.tsx, src/features/ui/input.tsx, src/features/ui/select.tsx
This pull request primarily focuses on improving the user interface and enhancing the codebase's structure. The most significant changes involve modifying the `Selectors` and `Input` components in the `selectors.tsx` and `input.tsx` files, respectively, and a substantial overhaul of the `Select` component in the `select.tsx` file.
Changes to `Selectors` and `Input` components:
* [`src/app/settings/admin/selectors.tsx`](diffhunk://#diff-d8c7a0319bdb53bcc2e684ece735ca738aa7582da4020f753306e673fbb441c8L40-R43): Simplified the styling of the div elements and changed the `Select` component's `value` prop and `groups` prop to `options` in the `Selectors` component. [[1]](diffhunk://#diff-d8c7a0319bdb53bcc2e684ece735ca738aa7582da4020f753306e673fbb441c8L40-R43) …
=> chore: Select component to match other inputs styling & fix default value

src/components/login/login.tsx, src/features/theme/theme-switch.tsx, src/features/ui/user-login-logout.tsx
This pull request includes changes primarily aimed at improving the readability and maintainability of the codebase by using React's `useCallback` hook. The hook is used to memorize callback functions across re-renders, which can help improve performance, especially in components that render often. The changes are spread across three files: `login.tsx`, `theme-switch.tsx`, and `user-login-logout.tsx`.
Changes in `login.tsx`:
* [`src/components/login/login.tsx`](diffhunk://#diff-b9f3108c1cbc50ef0bc46d49a290cf2c2903063aab1844baaf9e8c784c91f2e5R4): The `useCallback` hook is imported and used to create a memoized version of the `signIn` function, which is then used as the `onClick` handler for the `Button` component. This change can help improve performance by preventing unnecessary …
=> Improve code formatting and functions

src/features/common/services/cosmos-auth.ts, src/package-lock.json, src/package.json, src/public/whats-new.md, src/tests/unit/cosmos.test.ts
This pull request includes changes to improve the code organization and update dependencies. The most important changes include reordering imports in `cosmos-auth.ts`, updating the `lucide-react` dependency in `package.json`, adding a new version update in `whats-new.md`, and refactoring test code in `cosmos.test.ts`.
Code organization improvements:
* [`src/features/common/services/cosmos-auth.ts`](diffhunk://#diff-d892c4ec681b0c1ac1787c759407f5c973e45af7f83f108c345329d5537a126aL1-R4): Reordered the imports to follow best practices, moving the `logger` import to be after the `CosmosClient` import.
Dependency Updates:
* [`src/package.json`](diffhunk://#diff-cc5a2f170768969f124108ad3be7fdbcbed774c11774d99a87a3a78fef4ab97bL65-R65): Updated the `lucide-react` dependency from version `0.400.0` …
=> v163 release notes - lint fix on unit tests

src/components/chat/chat-row.tsx, src/features/chat/chat-services/chat-message-service.ts, src/features/chat/chat-ui/chat-message-container.tsx, src/features/chat/constants.ts, src/features/reporting/reporting-message-container.tsx, src/features/ui/assistant-buttons/rewrite-message-button.tsx
This pull request primarily focuses on enhancing the chat functionality in the application. The most significant changes include the addition of a new icon, refactoring of props in the `ChatRow` component, implementation of a warning for short input messages, and the integration of the chat thread lock status into various components.
Addition of new icon:
* [`src/components/chat/chat-row.tsx`](diffhunk://#diff-027a35f5584ceef68685cfaa6d21295fe676501f04e730543d13498cb70b5dd2L3-R3): The `SmilePlus` icon from `lucide-react` has been imported into the file.
Refactoring of `ChatRow` component:
* [`src/components/chat/chat-row.tsx`](diffhunk://#diff-027a35f5584ceef68685cfaa6d21295fe676501f04e730543d13498cb70b5dd2L22-R40): The `threadLocked` prop has been replaced with `lockMessage` in the …
=> Addition of Short Message Warning and better use of Context for disabling buttons when Chat Thread is Locked

src/components/chat/chat-file-transcription.tsx, src/components/chat/chat-transcript-change.tsx
This pull request primarily focuses on changes in the `src/components/chat/chat-file-transcription.tsx` and `src/components/chat/chat-transcript-change.tsx` files. The key modifications include the addition of new icons from `lucide-react`, changes in the `Button` components, and a slight adjustment in the text displayed in the `ChatTranscriptEditor` component.
Key changes:
* [`src/components/chat/chat-file-transcription.tsx`](diffhunk://#diff-1999aca0416f0b7591be8cb7d654a40e1f1fc14427393fbef6ea7a82be1f9ec9L3-R3): Imported new icons `Undo` and `Undo2` from `lucide-react` for use in the `Button` components.
* [`src/components/chat/chat-file-transcription.tsx`](diffhunk://#diff-1999aca0416f0b7591be8cb7d654a40e1f1fc14427393fbef6ea7a82be1f9ec9L84-R99): Adjusted the `Button` components in the …
=> feat: Add Undo and Undo2 icons to ChatFileTranscription component

src/features/settings/tenant-details/tenant-details-form.tsx
The code changes involve replacing the agency name variable in the tenant details form. This change ensures that the correct agency name is displayed in the context prompt message. The agency name is now retrieved from the {AGENCY_NAME} variable, which is regularly audited by the AI Unit.
=> feat: Replace agency name variable in tenant details form

src/features/chat/chat-services/chat-thread-service.ts, src/features/chat/models.ts
This pull request includes enhancements to the chat thread service and models by adding evaluation metrics. These changes aim to capture various performance and user satisfaction metrics for chat threads.
* [`src/features/chat/chat-services/chat-thread-service.ts`](diffhunk://#diff-bddad34450c7e7af3d06ffd22ebcde980e85c8af1017de49bfc10f96c7084758R257-R266): Added `evaluationMetrics` to the `CreateChatThread` function to track various performance and user satisfaction metrics.
* [`src/features/chat/models.ts`](diffhunk://#diff-f0481e710f6d6aec8cdd9f3707b9553d3e04d47c8bbcdea00d37b29e5b2f3d4cR98-R109): Introduced the `EvaluationMetrics` interface and added it to the `ChatThreadModel` to define and store metrics such as `outputLength`, `interactionTimeMin`, `numberOfCompletedTasks`, …
=> feat- added evaluationMetrics (null values) to chat thread

src/features/common/services/cosmos-auth.ts, src/features/common/services/cosmos.ts, src/tests/unit/cosmos.test.ts
This pull request includes changes refactoring the authentication process to use Azure Active Directory (AAD) credentials and simplifying the client creation logic.
* [`src/features/common/services/cosmos-auth.ts`](diffhunk://#diff-d892c4ec681b0c1ac1787c759407f5c973e45af7f83f108c345329d5537a126aL1-L48): Refactored to use Azure AD credentials (`DeviceCodeCredential` for development and `DefaultAzureCredential` for other environments) for Cosmos DB client creation. Removed the old token fetching and validation logic.
* [`src/features/common/services/cosmos.ts`](diffhunk://#diff-c268ff1a6fc191f99321155ee9ec7323f65e574819c9711177ad495e8059c428L1-R3): Updated to import the new Cosmos client creation function from `cosmos-auth.ts` and removed the old client creation logic.
* …
=> chore: fix unit tests
