src/features/user-management/user-service.ts

Amend user sign-in history logging to reduce uneccessary changes

Amend user sign-in history logging

---

src/features/auth/sign-in.ts
src/features/chat/chat-services/chat-message-service.ts

This pull request updates the setting SignIn for ChatMessage Migration. It includes the commit "Updated setting SignIn for ChatMessage Migration" and the file changes listed in the git patches.

Update setting SignIn for ChatMessage Migration

---

src/dockerfile
src/features/common/server-action-response.ts
src/package-lock.json
src/package.json

fix: remove unused zod package
update dockerfile

QGGPT-441 - Fix docker build and deploy for QChat

---

src/app-global.ts
src/app/hallucinations/page.tsx
src/app/terms/page.tsx
src/app/whats-new/page.tsx
src/features/change-log/app-version.ts
src/features/change-log/version-display.tsx
src/package-lock.json
src/package.json
src/public/whats-new.md

This pull request primarily addresses the version upgrade of the application from "1.4.2" to "1.4.3". The changes include updating the version number in multiple files, modifying the way `APP_VERSION` is exported and imported, and adding a new section in the `whats-new.md` file to document the updates in the new version. 
Here are the most important changes:
Version upgrade:
* [`src/app-global.ts`](diffhunk://#diff-6f6b4494ef9199e92a8afda39fbb184b4e854549a8dd44d0706e132a2b8fc3f2L1-R1): The `APP_VERSION` constant is now being exported directly and its value has been updated to "1.4.3".
* `src/package-lock.json` and `src/package.json`: The version number has been updated to "1.4.3". [[1]](diffhunk://#diff-998cefe66c8f4a3c44a608be658fb845884ddbff34d948ca6c751f57186054b7L3-R9) …

Update app-global.ts to version 1.4.3

---

src/next.config.js

This pull request updates the `connect-src` value in the `Content-Security-Policy` header. The new value includes additional domains for connecting to resources. This change improves the security and functionality of the application.

Update connect-src in Content-Security-Policy header

---

src/features/common/services/cosmos.ts

This pull request primarily focuses on improving the management of authentication tokens in the `cosmos.ts` file. The changes introduce a new `AuthToken` interface and a mechanism to automatically refresh the authentication token every 23 hours. The `CosmosInstance` function has been modified to be asynchronous and to use the new `AuthToken` interface. This change has also led to modifications in the `HistoryContainer`, `UserContainer`, and `TenantContainer` functions, which now await the `CosmosInstance` function instead of directly receiving an authentication token.
Token Management:
* [`src/features/common/services/cosmos.ts`](diffhunk://#diff-c268ff1a6fc191f99321155ee9ec7323f65e574819c9711177ad495e8059c428L2-R45): Introduced an `AuthToken` interface to manage authentication tokens and …

chore: Refactor CosmosInstance to use async/await

---

src/features/auth/auth-api.ts

This pull request updates the scope for Azure AD authentication in the `auth-api.ts` file. The previous scope included `offline_access`, which has been removed in this update.

Update auth-api.ts scope for Azure AD authentication

---

src/features/settings/tenant-details.form.tsx

This pull request introduces several changes to the `TenantDetailsForm` component in the `src/features/settings/tenant-details.form.tsx` file. The changes primarily focus on improving error handling and readability of the code. The most significant changes include wrapping API calls with try-catch blocks and replacing promise-based code with async-await syntax for better readability and error handling.
Here are the most important changes:
Error handling improvements:
* Wrapped API calls in try-catch blocks to handle any potential errors during API communication. This includes the API calls for updating context prompt, clearing context prompt, validating and submitting groups, deleting a group, and updating group login requirement. …

Refactor auth-api.ts to include tenantAdmin property in AuthToken interface

---

src/app-global.ts
src/features/ui/assistant-buttons/rewrite-message-button.tsx
src/package-lock.json
src/package.json
src/public/whats-new.md

This pull request primarily involves updates for the new version 1.4.7 of the application. The most important changes include updating the version number in various files, enhancing the text rewriting feature, and updating the 'what's new' section with the new version's details.
Version updates:
* [`src/app-global.ts`](diffhunk://#diff-6f6b4494ef9199e92a8afda39fbb184b4e854549a8dd44d0706e132a2b8fc3f2L1-R1): The `APP_VERSION` constant was updated from "1.4.6" to "1.4.7".
* [`src/package-lock.json`](diffhunk://#diff-998cefe66c8f4a3c44a608be658fb845884ddbff34d948ca6c751f57186054b7L3-R9): The version number was updated in multiple places from "1.4.6" to "1.4.7".
* [`src/package.json`](diffhunk://#diff-cc5a2f170768969f124108ad3be7fdbcbed774c11774d99a87a3a78fef4ab97bL3-R3): The version number …

feat: Update app version to 1.4.7 and package dependencies

---

src/features/chat/chat-services/chat-api.ts
src/features/chat/chat-ui/chat-input/chat-input.tsx
src/features/chat/models.ts

This pull request primarily includes changes to the chat functionality in the `src/features/chat` directory. The changes include the addition of a new model, `AssistantChatMessageModel`, modifications to the `ChatApi` function, changes to the `ChatInput` component, and an update to the `ChatMessageModel` interface.
Major changes include:
Addition of new models and updates to existing ones:
* [`src/features/chat/chat-services/chat-api.ts`](diffhunk://#diff-165fc4d4be73e722a9fcc419023d14d90a99a578802a1516032500b86d3f6ac1R7): Added `AssistantChatMessageModel` to the import statement.
* [`src/features/chat/models.ts`](diffhunk://#diff-f0481e710f6d6aec8cdd9f3707b9553d3e04d47c8bbcdea00d37b29e5b2f3d4cR63): Added `isPartial` as an optional field to `ChatMessageModel` interface.
Changes to handle …

implemented stop streaming and saving partial responses

---

src/app-global.ts
src/features/chat/chat-ui/chat-file/chat-file-ui.tsx
src/features/chat/chat-ui/chat-file/use-file-selection.ts
src/package-lock.json
src/package.json
src/public/whats-new.md

This pull request primarily involves the removal of a temporary experimental feature check and an update to the application version. The `shouldUseWhisper` function, which was temporarily used to check if the experimental whisper feature is enabled, has been removed. This function was used in the `useFileSelection` hook and the `ChatFileUI` component. The application version has been updated from 1.5.0 to 1.5.1 in several files.
Removal of temporary experimental feature check:
* [`src/features/chat/chat-ui/chat-file/chat-file-ui.tsx`](diffhunk://#diff-23dc59e35f50a335f6266f85434debf2eb4b0ab1cc70a842ce59bc67d6e5ab94L14-L16): Removed the `shouldUseWhisper` function, which was used to check if the experimental whisper feature is enabled.
* …

feat: Update app version to 1.5.1 and package dependencies

---

src/features/chat/chat-services/azure-cog-search/azure-cog-vector-store.ts

chore: Update Azure Cognitive Search filters to use 'search.in' function

Update Azure Cognitive Search filters to use 'search.in' function

---

src/features/chat/chat-services/chat-api-helper.ts
src/features/chat/chat-services/chat-api.ts

This pull request primarily focuses on introducing audio chat functionality to the chat services. It includes changes to the `chat-api-helper.ts` and `chat-api.ts` files in the `src/features/chat/chat-services/` directory. The most important changes are the addition of the `buildAudioChatMessages` function, the import of this function into `chat-api.ts`, and the integration of this function into the `ChatApi` function.
New Functionality:
* [`src/features/chat/chat-services/chat-api-helper.ts`](diffhunk://#diff-6d77056e441a1e3e83af3fb3c1d13c45e30a871dc6fe39be966b224dd004d3ffR10): Added the `FindAllChatDocumentsForCurrentUser` import and the `buildAudioChatMessages` function to handle audio chat messages. This function fetches all chat documents for the current user, builds the context from …

implemented audio chat context

---

src/app-global.ts
src/app/login-error/page.tsx
src/features/chat/chat-services/chat-document-service.ts
src/features/chat/chat-ui/chat-file/chat-file-ui.tsx
src/features/chat/models.ts
src/features/common/date-helper.ts
src/package-lock.json
src/package.json
src/public/whats-new.md

This pull request primarily focuses on updating the application version, modifying error messages, enhancing the document upload feature, and updating the release notes. The changes range from simple text updates to more complex modifications involving multiple files and functions.
Application version updates:
* `src/app-global.ts`, `src/package-lock.json`, and `src/package.json`: Updated the application version from 1.5.4 to 1.5.5. [[1]](diffhunk://#diff-6f6b4494ef9199e92a8afda39fbb184b4e854549a8dd44d0706e132a2b8fc3f2L1-R1) [[2]](diffhunk://#diff-998cefe66c8f4a3c44a608be658fb845884ddbff34d948ca6c751f57186054b7L3-R9) [[3]](diffhunk://#diff-cc5a2f170768969f124108ad3be7fdbcbed774c11774d99a87a3a78fef4ab97bL3-R3)
Error message modifications:
* …

Chat with File Preparedness

---

src/components/chat/chat-file-transcription.tsx
src/components/chat/chat-file-view.tsx
src/features/chat/chat-ui/chat-message-container.tsx
src/features/common/file-export.ts

This pull request primarily focuses on enhancing the transcription and reporting functionality of the chat component in the application. It introduces the ability to download a transcription report in addition to the existing transcription download functionality. Also, it modifies the file view and display of the chat component. 
Here are the key changes:
**Enhancements to Transcription Functionality:**
* [`src/components/chat/chat-file-transcription.tsx`](diffhunk://#diff-1999aca0416f0b7591be8cb7d654a40e1f1fc14427393fbef6ea7a82be1f9ec9L1-R12): Introduced a new function `onDownloadReport` to handle the downloading of transcription reports. Also, the file name format for downloads has been refined. [[1]](diffhunk://#diff-1999aca0416f0b7591be8cb7d654a40e1f1fc14427393fbef6ea7a82be1f9ec9L1-R12 …

Document and Transcript Transition Changes

---

src/app/layout.tsx

This pull request includes changes to the `RootLayout` function in the `src/app/layout.tsx` file. The changes involve adding new link elements for preconnecting to Google Analytics and Google Fonts, which can improve the loading performance of the website.
The most significant changes are:
* [`src/app/layout.tsx`](diffhunk://#diff-29d0a55f5ca1a9951042587f8b891bb4cd8b204f5bc855dc2468ed44cde2f5b3R62-R64): Added `link` elements for preconnecting to `https://www.google-analytics.com`, `https://fonts.googleapis.com`, and `https://fonts.gstatic.com`. This can help speed up the loading of these resources by establishing early connections.

Added preloads for analytics and fonts

---

src/app/footer.tsx
src/app/header.tsx
src/app/login-error/page.tsx
src/app/settings/admin/page.tsx
src/app/unauthorised/page.tsx
src/components/login/login.tsx
src/features/settings/settings-menu.tsx
src/features/settings/tenant-details/department-name.tsx
src/features/settings/tenant-details/domain-details.tsx
src/features/settings/tenant-details/support-email.tsx
src/features/ui/callout.tsx
src/features/ui/card-skeleton.tsx
src/features/ui/qldgovlogo.tsx
src/features/ui/qldgovminilogo.tsx
src/features/ui/tooltip-provider.tsx

This pull request primarily focuses on two types of changes: removal of unnecessary `React` imports and simplification of CSS class names and styles in the codebase. The `React` imports are no longer needed due to the recent updates in React that allow for JSX Transform, which eliminates the need for importing the `React` object in every file. The CSS changes simplify the class names and styles, making the code cleaner and more readable.
Removal of unnecessary `React` imports:
* [`src/app/footer.tsx`](diffhunk://#diff-0580493debe2676fb67a5ee98845d6a6430150b3d4e58e877714eb26ec960829L2): Removed unnecessary `React` import.
* [`src/app/header.tsx`](diffhunk://#diff-2db8d885551b66542d309eb0d4a563e3477bd18ac0ea7302c5bd06f2ceddda03L2): Removed unnecessary `React` import.
* …

chore: Remove unused React imports in code files

---

src/app/layout.tsx
src/app/login-error/page.tsx
src/components/announcement/agree-terms-and-conditions.tsx
src/components/announcement/whats-new-modal.tsx
src/components/login/login.tsx
src/components/markdown/code-block.tsx
src/features/chat/chat-menu/menu-item-actions.tsx
src/features/chat/chat-menu/menu-items.tsx
src/features/chat/chat-ui/chat-empty-state/chat-transcript-details.tsx
src/features/chat/chat-ui/chat-file/chat-file-slider.tsx
src/features/chat/chat-ui/chat-file/chat-file-ui.tsx
src/features/chat/chat-ui/chat-input/chat-input-menu.tsx
src/features/chat/chat-ui/chat-input/chat-input.tsx
src/features/reporting/reporting-message-container.tsx
src/features/reporting/reporting.tsx
src/features/settings/history.tsx
src/features/settings/tenant-details/administrators.tsx
src/features/settings/tenant-details/group-list.tsx
src/features/settings/tenant-details/tenant-details-form.tsx
src/features/settings/user-details/user-details-form.tsx
src/features/tenant-management/tenant-list.tsx
src/features/theme/theme-switch.tsx
src/features/ui/assistant-buttons/feedback-modal.tsx
src/features/ui/banner.tsx
src/features/ui/button.tsx
src/features/ui/dropdown-menu.tsx
src/features/user-management/user-list.tsx

This pull request primarily focuses on improving error handling, enhancing accessibility, and refining the user interface in various components of the application. The changes include the addition of error handling for session and application settings fetch operations, the usage of explicit types for state variables, improved error messages, and the addition of `ariaLabel` properties to several buttons for better accessibility. 
Error Handling:
* [`src/app/layout.tsx`](diffhunk://#diff-29d0a55f5ca1a9951042587f8b891bb4cd8b204f5bc855dc2468ed44cde2f5b3L52-R75): Added error handling for `getServerSession` and `GetApplicationSettings` functions. Now, in case of an error, a global error message will be displayed and the function will return a default value.
Accessibility Improvements:
* …

chore: Add aria labels to buttons for improved accessibility

---

src/features/ui/navbar.tsx

This pull request includes a minor change to the `NavBar` component in the `src/features/ui/navbar.tsx` file. The change modifies the `div` element that wraps each link in the navigation bar, adding a `relative` class to the existing classes. This likely allows for more flexible positioning of child elements within each navigation link.

Update navbar styling

---

src/features/auth/helpers.ts
src/features/chat/chat-services/utils.ts
src/features/chat/chat-ui/chat-empty-state/chat-style-selector.tsx
src/features/tenant-management/tenant-service.ts

This pull request primarily focuses on improving the case-insensitive handling of user identifiers and removing unnecessary comments in the `src/features/auth/helpers.ts` and `src/features/tenant-management/tenant-service.ts` files.
The most significant changes are as follows:
Changes to user identifier handling:
* [`src/features/auth/helpers.ts`](diffhunk://#diff-5268c7cd0a6006901c834178e512629f1e7fcd25d5ccda0fa59caa28c5a7385cL34-R35): In the `isTenantAdmin` function, the user identifier (either `userModel.upn` or `userModel.email`) is now converted to lowercase. The same change is applied to each administrator in the tenant's administrators list before checking if the user identifier is included. This ensures that the check is case-insensitive.
* …

Fixed Tenant Admin Comparison Error
